// src/routes/tools/[slug]/+page.svelte
<script lang="ts">
  import { page } from "$app/stores";
  import { Button } from "$lib/components/ui/button";
  import { Badge } from "$lib/components/ui/badge";
  import { Separator } from "$lib/components/ui/separator";
  import * as Avatar from "$lib/components/ui/avatar";
  import { ToolCard } from "$lib/components/tools";
  import {
    ChevronUp,
    ExternalLink,
    Star,
    Check,
    X,
    Monitor,
    Smartphone,
    Apple,
    Globe,
    Loader2,
  } from "@lucide/svelte";
  import { toast } from "svelte-sonner";
  import type { Pricing } from "@prisma/client";

  let { data } = $props();

  // Check if user is logged in
  const isLoggedIn = $derived(!!$page.data.user);

  // Local state for main tool upvote with override pattern
  let isUpvotedOverride = $state<boolean | null>(null);
  let upvoteCountOverride = $state<number | null>(null);
  let isLoading = $state(false);

  // Computed values that respect both props and local overrides
  const isUpvoted = $derived(isUpvotedOverride !== null ? isUpvotedOverride : data.isUpvoted);
  const upvoteCount = $derived(upvoteCountOverride !== null ? upvoteCountOverride : data.tool.upvoteCount);

  // Reset overrides when data changes
  $effect(() => {
    const _ = data.isUpvoted;
    isUpvotedOverride = null;
  });

  $effect(() => {
    const _ = data.tool.upvoteCount;
    upvoteCountOverride = null;
  });

  // Track upvotes for related tools with override pattern
  const initialRelatedUpvotes = $derived(new Set(data.relatedUpvotes));
  let relatedUpvoteOverrides = $state<Map<string, boolean>>(new Map());

  const relatedUpvotes = $derived.by(() => {
    const combined = new Set(initialRelatedUpvotes);
    for (const [toolId, upvoted] of relatedUpvoteOverrides) {
      if (upvoted) {
        combined.add(toolId);
      } else {
        combined.delete(toolId);
      }
    }
    return combined;
  });

  $effect(() => {
    const _ = data.relatedUpvotes;
    relatedUpvoteOverrides = new Map();
  });

  async function handleUpvote() {
    if (!isLoggedIn) {
      toast.error("Connectez-vous pour voter", {
        action: {
          label: "Se connecter",
          onClick: () => window.location.href = "/login",
        },
      });
      return;
    }

    if (isLoading) return;
    isLoading = true;

    // Optimistic update
    const previousUpvoted = isUpvoted;
    const previousCount = upvoteCount;
    isUpvotedOverride = !isUpvoted;
    upvoteCountOverride = isUpvotedOverride ? upvoteCount + 1 : upvoteCount - 1;

    try {
      const response = await fetch("/api/upvote", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ toolId: data.tool.id }),
      });

      if (!response.ok) {
        const error = await response.json();
        throw new Error(error.message || "Erreur lors du vote");
      }

      const result = await response.json();
      isUpvotedOverride = result.upvoted;
      upvoteCountOverride = result.upvoteCount;
    } catch (err) {
      // Revert optimistic update
      isUpvotedOverride = previousUpvoted;
      upvoteCountOverride = previousCount;
      toast.error(err instanceof Error ? err.message : "Erreur lors du vote");
    } finally {
      isLoading = false;
    }
  }

  function handleRelatedUpvoteChange(toolId: string, upvoted: boolean) {
    relatedUpvoteOverrides.set(toolId, upvoted);
    relatedUpvoteOverrides = new Map(relatedUpvoteOverrides);
  }

  const pricingLabels: Record<Pricing, { label: string; variant: "default" | "secondary" | "outline" | "destructive" }> = {
    FREE: { label: "Gratuit", variant: "secondary" },
    FREEMIUM: { label: "Freemium", variant: "outline" },
    PAID: { label: "Payant", variant: "default" },
    ENTERPRISE: { label: "Enterprise", variant: "destructive" },
  };

  const platformIcons: Record<string, typeof Globe> = {
    web: Globe,
    mac: Apple,
    windows: Monitor,
    ios: Smartphone,
    android: Smartphone,
    linux: Monitor,
  };

  function getInitials(name: string | null | undefined): string {
    if (!name) return "U";
    return name
      .split(" ")
      .map((n) => n[0])
      .join("")
      .toUpperCase()
      .slice(0, 2);
  }

  function formatDate(date: Date): string {
    return new Intl.DateTimeFormat("fr-FR", {
      day: "numeric",
      month: "long",
      year: "numeric",
    }).format(new Date(date));
  }
</script>

<svelte:head>
  <title>{data.tool.name} - Avis et Test | Productivité</title>
  <meta name="description" content={data.tool.tagline || data.tool.description || `Découvrez ${data.tool.name}, ses fonctionnalités, tarifs et avis utilisateurs.`} />
  <meta property="og:title" content="{data.tool.name} - Avis et Test | Productivité" />
  <meta property="og:description" content={data.tool.tagline || `Découvrez ${data.tool.name} et boostez votre productivité.`} />
  {#if data.tool.logo}
    <meta property="og:image" content={data.tool.logo} />
  {/if}
  <meta property="og:type" content="product" />
</svelte:head>

<div class="container mx-auto px-4 py-8">
  <!-- Breadcrumb -->
  <nav class="mb-6 text-sm text-neutral-500">
    <a href="/" class="hover:text-neutral-900">Accueil</a>
    <span class="mx-2">/</span>
    <a href="/tools" class="hover:text-neutral-900">Outils</a>
    <span class="mx-2">/</span>
    <a href="/categories/{data.tool.category.slug}" class="hover:text-neutral-900">{data.tool.category.name}</a>
    <span class="mx-2">/</span>
    <span class="text-neutral-900">{data.tool.name}</span>
  </nav>

  <div class="grid gap-8 lg:grid-cols-3">
    <!-- Main Content -->
    <div class="lg:col-span-2">
      <!-- Header -->
      <div class="flex items-start gap-6">
        <!-- Logo -->
        <div class="flex h-20 w-20 shrink-0 items-center justify-center overflow-hidden rounded-2xl border border-neutral-200 bg-white">
          {#if data.tool.logo}
            <img src={data.tool.logo} alt={data.tool.name} class="h-14 w-14 object-contain" />
          {:else}
            <span class="text-2xl font-bold text-neutral-400">{getInitials(data.tool.name)}</span>
          {/if}
        </div>

        <div class="flex-1">
          <div class="flex items-center gap-3 flex-wrap">
            <h1 class="text-3xl font-bold text-neutral-900">{data.tool.name}</h1>
            <Badge variant={pricingLabels[data.tool.pricing].variant}>
              {pricingLabels[data.tool.pricing].label}
            </Badge>
          </div>
          <p class="mt-2 text-lg text-neutral-600">{data.tool.tagline}</p>
          <div class="mt-4 flex items-center gap-4">
            <a
              href="/categories/{data.tool.category.slug}"
              class="text-sm font-medium hover:underline"
              style="color: {data.tool.category.color}"
            >
              {data.tool.category.name}
            </a>
            {#if data.avgRating > 0}
              <div class="flex items-center gap-1">
                <Star class="h-4 w-4 fill-yellow-400 text-yellow-400" />
                <span class="text-sm font-medium">{data.avgRating.toFixed(1)}</span>
                <span class="text-sm text-neutral-500">({data.tool._count.reviews} avis)</span>
              </div>
            {/if}
          </div>
        </div>

        <!-- Upvote Button -->
        <Button
          variant="outline"
          size="lg"
          class="flex h-auto flex-col gap-0 px-6 py-3 transition-all {isUpvoted
            ? 'border-orange-500 bg-orange-50 text-orange-600'
            : 'hover:border-orange-500 hover:bg-orange-50 hover:text-orange-600'}"
          onclick={handleUpvote}
          disabled={isLoading}
        >
          {#if isLoading}
            <Loader2 class="h-5 w-5 animate-spin" />
          {:else}
            <ChevronUp class="h-5 w-5 {isUpvoted ? 'fill-orange-600' : ''}" />
          {/if}
          <span class="text-lg font-bold">{upvoteCount}</span>
        </Button>
      </div>

      <!-- Actions -->
      <div class="mt-8 flex gap-4">
        {#if data.tool.website}
          <Button class="bg-gradient-to-r from-orange-500 to-rose-500 hover:from-orange-600 hover:to-rose-600" href={data.tool.website} target="_blank" rel="noopener noreferrer">
            Visiter le site
            <ExternalLink class="ml-2 h-4 w-4" />
          </Button>
        {/if}
      </div>

      <Separator class="my-8" />

      <!-- Description -->
      <section>
        <h2 class="text-xl font-bold text-neutral-900">Description</h2>
        <p class="mt-4 text-neutral-600 leading-relaxed whitespace-pre-line">
          {data.tool.description || "Aucune description disponible."}
        </p>
      </section>

      <!-- Features -->
      {#if data.tool.features.length > 0}
        <section class="mt-8">
          <h2 class="text-xl font-bold text-neutral-900">Fonctionnalités</h2>
          <ul class="mt-4 grid gap-2 sm:grid-cols-2">
            {#each data.tool.features as feature}
              <li class="flex items-center gap-2 text-neutral-600">
                <Check class="h-4 w-4 text-green-500" />
                {feature}
              </li>
            {/each}
          </ul>
        </section>
      {/if}

      <!-- Pros & Cons -->
      {#if data.tool.pros.length > 0 || data.tool.cons.length > 0}
        <section class="mt-8">
          <h2 class="text-xl font-bold text-neutral-900">Avantages & Inconvénients</h2>
          <div class="mt-4 grid gap-6 sm:grid-cols-2">
            {#if data.tool.pros.length > 0}
              <div class="rounded-xl border border-green-200 bg-green-50 p-4">
                <h3 class="font-semibold text-green-800">Avantages</h3>
                <ul class="mt-3 space-y-2">
                  {#each data.tool.pros as pro}
                    <li class="flex items-start gap-2 text-sm text-green-700">
                      <Check class="mt-0.5 h-4 w-4 shrink-0" />
                      {pro}
                    </li>
                  {/each}
                </ul>
              </div>
            {/if}
            {#if data.tool.cons.length > 0}
              <div class="rounded-xl border border-red-200 bg-red-50 p-4">
                <h3 class="font-semibold text-red-800">Inconvénients</h3>
                <ul class="mt-3 space-y-2">
                  {#each data.tool.cons as con}
                    <li class="flex items-start gap-2 text-sm text-red-700">
                      <X class="mt-0.5 h-4 w-4 shrink-0" />
                      {con}
                    </li>
                  {/each}
                </ul>
              </div>
            {/if}
          </div>
        </section>
      {/if}

      <!-- Reviews -->
      <section class="mt-8">
        <div class="flex items-center justify-between">
          <h2 class="text-xl font-bold text-neutral-900">Avis ({data.tool._count.reviews})</h2>
          <Button variant="outline">Laisser un avis</Button>
        </div>

        {#if data.tool.reviews.length > 0}
          <div class="mt-6 space-y-4">
            {#each data.tool.reviews as review}
              <div class="rounded-xl border border-neutral-200 bg-white p-4">
                <div class="flex items-center gap-3">
                  <Avatar.Root class="h-10 w-10">
                    {#if review.user.image}
                      <Avatar.Image src={review.user.image} alt={review.user.name || "Utilisateur"} />
                    {/if}
                    <Avatar.Fallback class="bg-gradient-to-br from-orange-500 to-rose-500 text-white text-sm">
                      {getInitials(review.user.name)}
                    </Avatar.Fallback>
                  </Avatar.Root>
                  <div>
                    <div class="font-medium text-neutral-900">{review.user.name || "Utilisateur"}</div>
                    <div class="text-sm text-neutral-500">{formatDate(review.createdAt)}</div>
                  </div>
                  <div class="ml-auto flex items-center gap-1">
                    {#each Array(5) as _, i}
                      <Star
                        class="h-4 w-4 {i < review.rating ? 'fill-yellow-400 text-yellow-400' : 'text-neutral-200'}"
                      />
                    {/each}
                  </div>
                </div>
                {#if review.title}
                  <h4 class="mt-3 font-medium text-neutral-900">{review.title}</h4>
                {/if}
                {#if review.content}
                  <p class="mt-2 text-sm text-neutral-600">{review.content}</p>
                {/if}
              </div>
            {/each}
          </div>
        {:else}
          <div class="mt-6 rounded-xl border border-neutral-200 bg-neutral-50 p-8 text-center">
            <p class="text-neutral-500">Aucun avis pour le moment. Soyez le premier à donner votre avis !</p>
          </div>
        {/if}
      </section>
    </div>

    <!-- Sidebar -->
    <div class="lg:col-span-1">
      <div class="sticky top-24 space-y-6">
        <!-- Info Card -->
        <div class="rounded-xl border border-neutral-200 bg-white p-6">
          <h3 class="font-semibold text-neutral-900">Informations</h3>

          <!-- Platforms -->
          {#if data.tool.platforms.length > 0}
            <div class="mt-4">
              <div class="text-sm font-medium text-neutral-500">Plateformes</div>
              <div class="mt-2 flex flex-wrap gap-2">
                {#each data.tool.platforms as platform}
                  <Badge variant="secondary" class="capitalize">
                    {platform}
                  </Badge>
                {/each}
              </div>
            </div>
          {/if}

          <!-- Website -->
          {#if data.tool.website}
            <div class="mt-4">
              <div class="text-sm font-medium text-neutral-500">Site web</div>
              <a
                href={data.tool.website}
                target="_blank"
                rel="noopener noreferrer"
                class="mt-1 flex items-center gap-1 text-sm text-orange-600 hover:underline"
              >
                {new URL(data.tool.website).hostname}
                <ExternalLink class="h-3 w-3" />
              </a>
            </div>
          {/if}

          <!-- Pricing -->
          <div class="mt-4">
            <div class="text-sm font-medium text-neutral-500">Tarification</div>
            <Badge variant={pricingLabels[data.tool.pricing].variant} class="mt-1">
              {pricingLabels[data.tool.pricing].label}
            </Badge>
          </div>
        </div>

        <!-- Related Tools -->
        {#if data.relatedTools.length > 0}
          <div class="rounded-xl border border-neutral-200 bg-white p-6">
            <h3 class="font-semibold text-neutral-900">Outils similaires</h3>
            <div class="mt-4 space-y-3">
              {#each data.relatedTools as tool}
                <a
                  href="/tools/{tool.slug}"
                  class="flex items-center gap-3 rounded-lg p-2 transition-colors hover:bg-neutral-50"
                >
                  <div class="flex h-10 w-10 shrink-0 items-center justify-center overflow-hidden rounded-lg border border-neutral-100 bg-neutral-50">
                    {#if tool.logo}
                      <img src={tool.logo} alt={tool.name} class="h-6 w-6 object-contain" />
                    {:else}
                      <span class="text-xs font-bold text-neutral-400">{getInitials(tool.name)}</span>
                    {/if}
                  </div>
                  <div class="flex-1 min-w-0">
                    <div class="font-medium text-neutral-900 truncate">{tool.name}</div>
                    <div class="text-xs text-neutral-500 truncate">{tool.tagline}</div>
                  </div>
                  <div class="flex items-center gap-1 text-sm text-neutral-400">
                    <ChevronUp class="h-4 w-4" />
                    {tool.upvoteCount}
                  </div>
                </a>
              {/each}
            </div>
          </div>
        {/if}
      </div>
    </div>
  </div>
</div>

// src/app/(frontend)/tools/[slug]/page.tsx
import { Metadata } from 'next'
import Image from 'next/image'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import {
  ArrowLeft,
  ArrowUpRight,
  Check,
  X,
  Globe,
  Tag,
  Layers,
} from 'lucide-react'

import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { UpvoteButton } from '@/components/tools/upvote-button'
import { PricingBadge } from '@/components/ui/pricing-badge'
import { PlatformIcons } from '@/components/ui/platform-icons'
import { ToolCard } from '@/components/tools/tool-card'
import { getToolBySlug, getTools } from '@/lib/actions/tools'

interface ToolPageProps {
  params: Promise<{ slug: string }>
}

export async function generateMetadata({
  params,
}: ToolPageProps): Promise<Metadata> {
  const { slug } = await params
  const tool = await getToolBySlug(slug)

  if (!tool) {
    return {
      title: 'Outil non trouvé | productivite.io',
    }
  }

  return {
    title: `${tool.name} - ${tool.tagline} | productivite.io`,
    description: tool.description,
    openGraph: {
      title: `${tool.name} - ${tool.tagline}`,
      description: tool.description,
      images: tool.logo ? [tool.logo] : [],
    },
  }
}

// Dynamic page - no static params needed with Payload CMS
export const dynamic = 'force-dynamic'

export default async function ToolPage({ params }: ToolPageProps) {
  const { slug } = await params
  const tool = await getToolBySlug(slug)

  if (!tool) {
    notFound()
  }

  // Get related tools (same category, excluding current)
  const relatedResult = await getTools({
    category: tool.category.slug,
    limit: 4,
    sort: 'popular',
  })
  const relatedTools = relatedResult.tools.filter((t) => t.id !== tool.id).slice(0, 3)

  return (
    <div className="flex flex-col">
      {/* Breadcrumb */}
      <div className="border-b bg-muted/30">
        <div className="mx-auto max-w-7xl px-4 py-4 sm:px-6 lg:px-8">
          <nav className="flex items-center gap-2 text-sm text-muted-foreground">
            <Link href="/tools" className="flex items-center gap-1 hover:text-foreground">
              <ArrowLeft className="h-4 w-4" />
              Tous les outils
            </Link>
            <span>/</span>
            <Link
              href={`/categories/${tool.category.slug}`}
              className="hover:text-foreground"
            >
              {tool.category.name}
            </Link>
            <span>/</span>
            <span className="text-foreground">{tool.name}</span>
          </nav>
        </div>
      </div>

      {/* Hero Section */}
      <section className="border-b py-12">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col gap-8 lg:flex-row lg:items-start lg:justify-between">
            {/* Left: Tool Info */}
            <div className="flex flex-1 gap-6">
              {/* Logo */}
              <div className="flex h-24 w-24 shrink-0 items-center justify-center overflow-hidden rounded-2xl border bg-background shadow-sm">
                {tool.logo ? (
                  <Image
                    src={tool.logo}
                    alt={tool.name}
                    width={96}
                    height={96}
                    className="h-full w-full object-cover"
                  />
                ) : (
                  <span className="text-3xl font-bold text-muted-foreground">
                    {tool.name.charAt(0)}
                  </span>
                )}
              </div>

              {/* Info */}
              <div className="flex-1">
                <div className="flex flex-wrap items-center gap-3">
                  <h1 className="text-3xl font-bold sm:text-4xl">{tool.name}</h1>
                  <PricingBadge pricing={tool.pricing} />
                </div>
                <p className="mt-2 text-lg text-muted-foreground">
                  {tool.tagline}
                </p>

                {/* Meta */}
                <div className="mt-4 flex flex-wrap items-center gap-4 text-sm text-muted-foreground">
                  <Link
                    href={`/categories/${tool.category.slug}`}
                    className="flex items-center gap-1 hover:text-foreground"
                  >
                    <Tag className="h-4 w-4" />
                    {tool.category.name}
                  </Link>
                  <div className="flex items-center gap-1">
                    <Layers className="h-4 w-4" />
                    <PlatformIcons platforms={tool.platforms} showLabels />
                  </div>
                </div>
              </div>
            </div>

            {/* Right: Actions */}
            <div className="flex flex-col gap-3 sm:flex-row lg:flex-col">
              <UpvoteButton
                toolId={tool.id}
                initialCount={tool.upvoteCount}
                size="lg"
              />
              <Button size="lg" asChild>
                <a
                  href={tool.website}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="gap-2"
                >
                  <Globe className="h-4 w-4" />
                  Visiter le site
                  <ArrowUpRight className="h-4 w-4" />
                </a>
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* Main Content */}
      <section className="py-12">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="grid gap-8 lg:grid-cols-3">
            {/* Left: Description */}
            <div className="lg:col-span-2">
              <Card>
                <CardHeader>
                  <CardTitle>Description</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-muted-foreground leading-relaxed">
                    {tool.description}
                  </p>
                </CardContent>
              </Card>

              {/* Features */}
              {tool.features && tool.features.length > 0 && (
                <Card className="mt-6">
                  <CardHeader>
                    <CardTitle>Fonctionnalités clés</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <ul className="grid gap-3 sm:grid-cols-2">
                      {tool.features.map((feature, index) => (
                        <li key={index} className="flex items-start gap-2">
                          <Check className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
                          <span className="text-sm">{feature}</span>
                        </li>
                      ))}
                    </ul>
                  </CardContent>
                </Card>
              )}

              {/* Pros & Cons */}
              <div className="mt-6 grid gap-6 sm:grid-cols-2">
                {/* Pros */}
                {tool.pros && tool.pros.length > 0 && (
                  <Card>
                    <CardHeader>
                      <CardTitle className="flex items-center gap-2 text-green-600">
                        <Check className="h-5 w-5" />
                        Points forts
                      </CardTitle>
                    </CardHeader>
                    <CardContent>
                      <ul className="space-y-2">
                        {tool.pros.map((pro, index) => (
                          <li key={index} className="flex items-start gap-2 text-sm">
                            <Check className="mt-0.5 h-4 w-4 shrink-0 text-green-600" />
                            {pro}
                          </li>
                        ))}
                      </ul>
                    </CardContent>
                  </Card>
                )}

                {/* Cons */}
                {tool.cons && tool.cons.length > 0 && (
                  <Card>
                    <CardHeader>
                      <CardTitle className="flex items-center gap-2 text-red-600">
                        <X className="h-5 w-5" />
                        Points faibles
                      </CardTitle>
                    </CardHeader>
                    <CardContent>
                      <ul className="space-y-2">
                        {tool.cons.map((con, index) => (
                          <li key={index} className="flex items-start gap-2 text-sm">
                            <X className="mt-0.5 h-4 w-4 shrink-0 text-red-600" />
                            {con}
                          </li>
                        ))}
                      </ul>
                    </CardContent>
                  </Card>
                )}
              </div>
            </div>

            {/* Right: Sidebar */}
            <div className="space-y-6">
              {/* Quick Info */}
              <Card>
                <CardHeader>
                  <CardTitle>Informations</CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="flex items-center justify-between">
                    <span className="text-sm text-muted-foreground">
                      Catégorie
                    </span>
                    <Link
                      href={`/categories/${tool.category.slug}`}
                      className="text-sm font-medium hover:underline"
                    >
                      {tool.category.name}
                    </Link>
                  </div>
                  <div className="flex items-center justify-between">
                    <span className="text-sm text-muted-foreground">
                      Tarification
                    </span>
                    <PricingBadge pricing={tool.pricing} />
                  </div>
                  <div className="flex items-center justify-between">
                    <span className="text-sm text-muted-foreground">
                      Plateformes
                    </span>
                    <PlatformIcons platforms={tool.platforms} />
                  </div>
                  <div className="flex items-center justify-between">
                    <span className="text-sm text-muted-foreground">Upvotes</span>
                    <span className="font-semibold">{tool.upvoteCount}</span>
                  </div>
                </CardContent>
              </Card>

              {/* CTA */}
              <Card className="bg-primary text-primary-foreground">
                <CardContent className="pt-6">
                  <h3 className="font-semibold">Vous utilisez {tool.name} ?</h3>
                  <p className="mt-2 text-sm text-primary-foreground/80">
                    Partagez votre expérience et aidez les autres utilisateurs.
                  </p>
                  <Button variant="secondary" className="mt-4 w-full">
                    Laisser un avis
                  </Button>
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </section>

      {/* Related Tools */}
      {relatedTools.length > 0 && (
        <section className="border-t bg-muted/30 py-12">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <div className="flex items-center justify-between">
              <h2 className="text-2xl font-bold">Outils similaires</h2>
              <Button variant="ghost" asChild>
                <Link
                  href={`/categories/${tool.category.slug}`}
                  className="gap-2"
                >
                  Voir tous
                  <ArrowUpRight className="h-4 w-4" />
                </Link>
              </Button>
            </div>
            <div className="mt-6 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
              {relatedTools.map((relatedTool) => (
                <ToolCard key={relatedTool.id} tool={relatedTool} />
              ))}
            </div>
          </div>
        </section>
      )}
    </div>
  )
}
