// src/app/(frontend)/categories/[slug]/page.tsx
import { Metadata } from 'next'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { ArrowLeft, ArrowRight } from 'lucide-react'
import * as LucideIcons from 'lucide-react'

import { Button } from '@/components/ui/button'
import { ToolCard } from '@/components/tools/tool-card'
import { getCategoryBySlug, getToolsByCategory, getCategories } from '@/lib/actions/tools'
import type { LucideIcon } from 'lucide-react'

interface CategoryPageProps {
  params: Promise<{ slug: string }>
}

export async function generateMetadata({
  params,
}: CategoryPageProps): Promise<Metadata> {
  const { slug } = await params
  const category = await getCategoryBySlug(slug)

  if (!category) {
    return {
      title: 'Catégorie non trouvée | productivite.io',
    }
  }

  return {
    title: `Outils ${category.name} | productivite.io`,
    description:
      category.description ||
      `Découvrez les meilleurs outils ${category.name.toLowerCase()} pour améliorer votre productivité.`,
  }
}

// Dynamic page - no static params needed with Payload CMS
export const dynamic = 'force-dynamic'

export default async function CategoryPage({ params }: CategoryPageProps) {
  const { slug } = await params

  // Fetch category, tools in category, and all categories for "Other categories" section
  const [category, categoryTools, allCategories] = await Promise.all([
    getCategoryBySlug(slug),
    getToolsByCategory(slug),
    getCategories(),
  ])

  if (!category) {
    notFound()
  }

  // Get icon component
  const IconComponent = category.icon
    ? (LucideIcons[category.icon as keyof typeof LucideIcons] as LucideIcon)
    : null

  return (
    <div className="flex flex-col">
      {/* Header */}
      <section
        className={`border-b py-12 ${category.color || 'bg-muted/30'}`}
      >
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          {/* Breadcrumb */}
          <nav className="mb-6 flex items-center gap-2 text-sm text-muted-foreground">
            <Link href="/categories" className="flex items-center gap-1 hover:text-foreground">
              <ArrowLeft className="h-4 w-4" />
              Catégories
            </Link>
            <span>/</span>
            <span className="text-foreground">{category.name}</span>
          </nav>

          <div className="flex items-center gap-4">
            {IconComponent && (
              <div className="flex h-14 w-14 items-center justify-center rounded-xl bg-background shadow-sm">
                <IconComponent className="h-7 w-7 text-primary" />
              </div>
            )}
            <div>
              <h1 className="text-3xl font-bold">{category.name}</h1>
              {category.description && (
                <p className="mt-1 text-muted-foreground">
                  {category.description}
                </p>
              )}
              <p className="mt-2 text-sm text-muted-foreground">
                {categoryTools.length} outil{categoryTools.length > 1 ? 's' : ''}{' '}
                dans cette catégorie
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Tools Grid */}
      <section className="py-12">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          {categoryTools.length > 0 ? (
            <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
              {categoryTools.map((tool) => (
                <ToolCard key={tool.id} tool={tool} />
              ))}
            </div>
          ) : (
            <div className="flex flex-col items-center justify-center rounded-lg border border-dashed py-16">
              <h3 className="mb-2 text-lg font-semibold">
                Aucun outil pour l&apos;instant
              </h3>
              <p className="mb-4 text-center text-muted-foreground">
                Cette catégorie ne contient pas encore d&apos;outils.
              </p>
              <Button asChild>
                <Link href="/submit">Proposer un outil</Link>
              </Button>
            </div>
          )}
        </div>
      </section>

      {/* Other Categories */}
      <section className="border-t bg-muted/30 py-12">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between">
            <h2 className="text-2xl font-bold">Autres catégories</h2>
            <Button variant="ghost" asChild>
              <Link href="/categories" className="gap-2">
                Voir toutes
                <ArrowRight className="h-4 w-4" />
              </Link>
            </Button>
          </div>
          <div className="mt-6 flex flex-wrap gap-3">
            {allCategories
              .filter((c) => c.id !== category.id)
              .map((otherCategory) => {
                const OtherIcon = otherCategory.icon
                  ? (LucideIcons[
                      otherCategory.icon as keyof typeof LucideIcons
                    ] as LucideIcon)
                  : null
                return (
                  <Link
                    key={otherCategory.id}
                    href={`/categories/${otherCategory.slug}`}
                    className="flex items-center gap-2 rounded-full border bg-background px-4 py-2 text-sm font-medium transition-colors hover:border-primary hover:text-primary"
                  >
                    {OtherIcon && <OtherIcon className="h-4 w-4" />}
                    {otherCategory.name}
                  </Link>
                )
              })}
          </div>
        </div>
      </section>
    </div>
  )
}

// src/routes/categories/[slug]/+page.svelte
<script lang="ts">
  import { page } from "$app/stores";
  import { goto } from "$app/navigation";
  import { Button } from "$lib/components/ui/button";
  import * as DropdownMenu from "$lib/components/ui/dropdown-menu";
  import * as Icons from "@lucide/svelte";
  import { ToolCard } from "$lib/components/tools";
  import { SlidersHorizontal } from "@lucide/svelte";

  let { data } = $props();

  // Check if user is logged in from layout data
  const isLoggedIn = $derived(!!$page.data.user);

  // Track upvotes locally for reactivity - use $derived.by to sync with props
  const initialUpvotes = $derived(new Set(data.userUpvotes));
  let localUpvoteOverrides = $state<Map<string, boolean>>(new Map());

  // Combined view of upvotes
  const userUpvotes = $derived.by(() => {
    const combined = new Set(initialUpvotes);
    for (const [toolId, upvoted] of localUpvoteOverrides) {
      if (upvoted) {
        combined.add(toolId);
      } else {
        combined.delete(toolId);
      }
    }
    return combined;
  });

  // Reset local overrides when data changes
  $effect(() => {
    const _ = data.userUpvotes;
    localUpvoteOverrides = new Map();
  });

  function handleUpvoteChange(toolId: string, upvoted: boolean) {
    localUpvoteOverrides.set(toolId, upvoted);
    localUpvoteOverrides = new Map(localUpvoteOverrides); // Trigger reactivity
  }

  const sortOptions = [
    { value: "popular", label: "Plus populaires" },
    { value: "recent", label: "Plus récents" },
    { value: "name", label: "Alphabétique" },
  ];

  function updateSort(sort: string) {
    const params = new URLSearchParams($page.url.searchParams);
    params.set("sort", sort);
    goto(`/categories/${data.category.slug}?${params.toString()}`);
  }

  const currentSort = $derived(
    sortOptions.find((o) => o.value === data.sort) || sortOptions[0]
  );

  // Dynamically get the icon component
  const IconComponent = $derived(
    (Icons as unknown as Record<string, typeof Icons.Folder>)[data.category.icon] || Icons.Folder
  );
</script>

<svelte:head>
  <title>Outils {data.category.name} - Productivité</title>
  <meta name="description" content={data.category.description || `Découvrez les ${data.tools.length} meilleurs outils de ${data.category.name} pour booster votre productivité.`} />
  <meta property="og:title" content="Outils {data.category.name} - Productivité" />
  <meta property="og:description" content={data.category.description || `Les meilleurs outils de ${data.category.name}`} />
</svelte:head>

<div class="container mx-auto px-4 py-8">
  <!-- Breadcrumb -->
  <nav class="mb-6 text-sm text-neutral-500">
    <a href="/" class="hover:text-neutral-900">Accueil</a>
    <span class="mx-2">/</span>
    <a href="/categories" class="hover:text-neutral-900">Catégories</a>
    <span class="mx-2">/</span>
    <span class="text-neutral-900">{data.category.name}</span>
  </nav>

  <!-- Header -->
  <div class="mb-8 flex items-start gap-4">
    <div
      class="flex h-16 w-16 shrink-0 items-center justify-center rounded-2xl"
      style="background-color: {data.category.color}20"
    >
      <IconComponent class="h-8 w-8" style="color: {data.category.color}" />
    </div>
    <div>
      <h1 class="text-3xl font-bold text-neutral-900">{data.category.name}</h1>
      {#if data.category.description}
        <p class="mt-2 text-neutral-600">{data.category.description}</p>
      {/if}
      <p class="mt-2 text-sm text-neutral-500">{data.tools.length} outils</p>
    </div>
  </div>

  <!-- Sort -->
  <div class="mb-6 flex justify-end">
    <DropdownMenu.Root>
      <DropdownMenu.Trigger
        class="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 border border-input bg-background shadow-sm hover:bg-accent hover:text-accent-foreground h-8 px-3 py-2"
      >
        <SlidersHorizontal class="h-4 w-4" />
        {currentSort.label}
      </DropdownMenu.Trigger>
      <DropdownMenu.Content>
        {#each sortOptions as option}
          <DropdownMenu.Item onclick={() => updateSort(option.value)}>
            {option.label}
          </DropdownMenu.Item>
        {/each}
      </DropdownMenu.Content>
    </DropdownMenu.Root>
  </div>

  <!-- Tools list -->
  {#if data.tools.length > 0}
    <div class="space-y-3">
      {#each data.tools as tool, i}
        <ToolCard
          {tool}
          rank={i + 1}
          {isLoggedIn}
          upvoted={userUpvotes.has(tool.id)}
          onUpvoteChange={handleUpvoteChange}
        />
      {/each}
    </div>
  {:else}
    <div class="flex flex-col items-center justify-center py-16 text-center">
      <div class="mb-4 text-6xl">📭</div>
      <h2 class="text-xl font-semibold text-neutral-900">Aucun outil dans cette catégorie</h2>
      <p class="mt-2 text-neutral-600">
        Soyez le premier à soumettre un outil dans cette catégorie !
      </p>
      <Button class="mt-4" href="/submit">
        Soumettre un outil
      </Button>
    </div>
  {/if}
</div>
